name: "Push Version Tag"
description: "Reads version from .version file, updates the tag, and adds changelog"
author: "Falokut"

inputs:
  version_file:
    description: "Path to the .version file"
    required: false
    default: ".version"
  changelog_file:
    description: "Path to the changelog file"
    required: false
    default: "changelogs.md"
  GH_TOKEN:
    description: "GitHub token for authentication"
    required: true

outputs:
  version:
    description: "Version from the .version file"
  changelog_entry:
    description: "Changelog entry for the version"

runs:
  using: "composite"
  steps:
    - name: Read version from file
      id: get_version
      run: |
        # ✅ Чтение версии из файла (.version) без пробелов
        VERSION=$(cat ${{ inputs.version_file }} | tr -d '\n')
        TAG_NAME="v${VERSION}"  # Добавляем префикс "v" для тегов и changelog

        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Delete existing tag if exists
      run: |
        git tag -d $TAG_NAME || true
        git push origin :refs/tags/$TAG_NAME || true
      shell: bash

    - name: Read Changelog
      id: changelog
      run: |
        echo "🔍 Ищем изменения для тега: $TAG_NAME"

        CHANGELOG_ENTRY=$(awk -v tag="## $TAG_NAME" '
        BEGIN {found=0}
        $0 == tag {found=1; next}
        /^## v[0-9]+\.[0-9]+\.[0-9]+/ && found {exit}
        found {print}
        ' ${{ inputs.changelog_file }})

        if [ -z "$CHANGELOG_ENTRY" ]; then
          echo "❌ Не удалось найти changelog для версии $TAG_NAME"
          exit 1
        fi

        echo "CHANGELOG_ENTRY<<EOF" >> $GITHUB_ENV
        echo "$CHANGELOG_ENTRY" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        echo "changelog_entry<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG_ENTRY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get Commit Metadata
      id: commit_metadata
      run: |
        COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
        COMMIT_AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
        echo "COMMIT_AUTHOR_EMAIL=${COMMIT_AUTHOR_EMAIL}" >> $GITHUB_ENV
        echo "COMMIT_AUTHOR_NAME=${COMMIT_AUTHOR_NAME}" >> $GITHUB_ENV
      shell: bash

    - name: Create new tag
      run: |
        git config --global user.email "${COMMIT_AUTHOR_EMAIL}"
        git config --global user.name "${COMMIT_AUTHOR_NAME}"

        git tag -a $TAG_NAME -m "Release ${VERSION}" -m "${CHANGELOG_ENTRY}"
        git push origin $TAG_NAME --quiet
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
      shell: bash